### ISSUE TITLE
Small typo in Equ. 11

### ISSUE THREAD

**Issue by artexety** [AozhongZhang/COMQ#1]
First of all, excellent job. The results of your work are truly remarkable.

Upon attempting to implement your method, I encountered a small typo in [Equation 11](https://arxiv.org/pdf/2403.07134.pdf#equation.1.3.11). Instead of:

![image](https://github.com/AozhongZhang/COMQ/assets/50674639/1ca52b66-5905-4492-85bb-c41f983b42c0)
it should be:
![image](https://github.com/AozhongZhang/COMQ/assets/50674639/3882308a-e803-43db-8906-72eb01f57e13)

**Comment by AozhongZhang** [comment]
Thanks for pointing it out. We will fix it.
